### ISSUE TITLE
Tela de cadastrar atendente

### ISSUE THREAD

**Issue by thelink2012** [fisufba/fisufba-client#12]

**Comment by gabrieleluz** [comment]
@thelink2012  Vou considerar que um atendente precisa de nome, e-mail, cpf e senha, ok? Qualquer coisa a gente vê.

**Comment by thelink2012** [comment]
Tranquilo. Sim, atendente precisa de senha.

Em qui, 16 de mai de 2019 22:45, Gabriele Luz <notifications@github.com>
escreveu:

**Comment by gabrieleluz** [comment]
Lista de dados atualizada de acordo com o diagrama de classes:
Nome, cpf, e-mail, telefone, senha
